## 1. Data Understanding & Loading

In [146]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer , KNNImputer
from sklearn.preprocessing import StandardScaler , LabelEncoder , OrdinalEncoder , OneHotEncoder,StandardScaler, MinMaxScaler
from ydata_profiling import ProfileReport

c:\Users\RUDRA JATIN GAYWALA\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [123]:
df1 = pd.read_csv('C:\\Users\\RUDRA JATIN GAYWALA\\OneDrive\\Desktop\\ML-projects\\pr exam\\users - users.csv.csv')
df1

    user_id            name  age  gender           city registration_date
0     U0001   Vihaan Sharma   35   Other         Jaipur        2022-09-08
1     U0002       Sai Reddy   30   Other      Hyderabad        2023-11-24
2     U0003    Aarohi Gupta   37   Other         Indore        2022-02-02
3     U0004     Aarav Gupta   44    Male        Kolkata        2023-06-02
4     U0005     Sara Sharma   30   Other        Chennai        2024-01-04
..      ...             ...  ...     ...            ...               ...
195   U0196  Kabir Kulkarni   35   Other          Patna        2024-08-01
196   U0197       Kabir Roy   24    Male          Thane        2023-12-07
197   U0198      Kabir Bose   33  Female  Visakhapatnam        2023-07-07
198   U0199       Meera Roy   32    Male      Ghaziabad        2022-02-10
199   U0200      Kiara Nair   22   Other         Jaipur        2022-01-27

[200 rows x 6 columns]

In [124]:
df2 = pd.read_json('C:\\Users\\RUDRA JATIN GAYWALA\\OneDrive\\Desktop\\ML-projects\\pr exam\\sales.json')
df2

    transaction_id user_id product_id  amount payment_type       date
0          T000001   U0024       P015   67.67       Wallet 2023-02-12
1          T000002   U0196       P044   76.44          UPI 2023-03-24
2          T000003   U0196       P049  104.57   Debit Card 2025-08-21
3          T000004   U0133       P042  102.75  Net Banking 2024-07-23
4          T000005   U0047       P038   23.89  Net Banking 2025-10-04
..             ...     ...        ...     ...          ...        ...
995        T000996   U0178       P043   71.11  Credit Card 2025-02-20
996        T000997   U0100       P027   53.96       Wallet 2024-10-02
997        T000998   U0142       P004   76.06  Credit Card 2024-05-29
998        T000999   U0052       P040   62.45  Net Banking 2024-04-06
999        T001000   U0163       P046  123.78       Wallet 2025-01-23

[1000 rows x 6 columns]

In [125]:
with open('C:\\Users\\RUDRA JATIN GAYWALA\\OneDrive\\Desktop\\ML-projects\\pr exam\\inventory.sql','r') as file:
  df3 = file.readlines()

In [126]:
df1.head()

  user_id           name  age gender       city registration_date
0   U0001  Vihaan Sharma   35  Other     Jaipur        2022-09-08
1   U0002      Sai Reddy   30  Other  Hyderabad        2023-11-24
2   U0003   Aarohi Gupta   37  Other     Indore        2022-02-02
3   U0004    Aarav Gupta   44   Male    Kolkata        2023-06-02
4   U0005    Sara Sharma   30  Other    Chennai        2024-01-04

In [127]:
df2.head()

  transaction_id user_id product_id  amount payment_type       date
0        T000001   U0024       P015   67.67       Wallet 2023-02-12
1        T000002   U0196       P044   76.44          UPI 2023-03-24
2        T000003   U0196       P049  104.57   Debit Card 2025-08-21
3        T000004   U0133       P042  102.75  Net Banking 2024-07-23
4        T000005   U0047       P038   23.89  Net Banking 2025-10-04

In [128]:
print(df3[:5])

['-- inventory.sql\n', '-- Create products table and insert sample rows\n', 'DROP TABLE IF EXISTS products;\n', 'CREATE TABLE products (\n', '    product_id TEXT PRIMARY KEY,\n']

In [129]:
df1.dtypes

user_id              object
name                 object
age                   int64
gender               object
city                 object
registration_date    object
dtype: object

In [130]:
df2.dtypes

transaction_id            object
user_id                   object
product_id                object
amount                   float64
payment_type              object
date              datetime64[ns]
dtype: object

In [131]:
df1.isnull().sum()

user_id              0
name                 0
age                  0
gender               0
city                 0
registration_date    0
dtype: int64

In [132]:
df2.isnull().sum()

transaction_id    0
user_id           0
product_id        0
amount            0
payment_type      0
date              0
dtype: int64

In [133]:
df1[df1.isnull().any(axis=1)]

Empty DataFrame
Columns: [user_id, name, age, gender, city, registration_date]
Index: []

In [134]:
df2[df2.isnull().any(axis=1)]

Empty DataFrame
Columns: [transaction_id, user_id, product_id, amount, payment_type, date]
Index: []

## 2. Data Cleaning

In [135]:
df1['age'] = SimpleImputer(strategy='mean').fit_transform(df1[['age']])
df1

    user_id            name   age  gender           city registration_date
0     U0001   Vihaan Sharma  35.0   Other         Jaipur        2022-09-08
1     U0002       Sai Reddy  30.0   Other      Hyderabad        2023-11-24
2     U0003    Aarohi Gupta  37.0   Other         Indore        2022-02-02
3     U0004     Aarav Gupta  44.0    Male        Kolkata        2023-06-02
4     U0005     Sara Sharma  30.0   Other        Chennai        2024-01-04
..      ...             ...   ...     ...            ...               ...
195   U0196  Kabir Kulkarni  35.0   Other          Patna        2024-08-01
196   U0197       Kabir Roy  24.0    Male          Thane        2023-12-07
197   U0198      Kabir Bose  33.0  Female  Visakhapatnam        2023-07-07
198   U0199       Meera Roy  32.0    Male      Ghaziabad        2022-02-10
199   U0200      Kiara Nair  22.0   Other         Jaipur        2022-01-27

[200 rows x 6 columns]

In [136]:
df2['amount'] = SimpleImputer(strategy='mean').fit_transform(df2[['amount']])
df2

    transaction_id user_id product_id  amount payment_type       date
0          T000001   U0024       P015   67.67       Wallet 2023-02-12
1          T000002   U0196       P044   76.44          UPI 2023-03-24
2          T000003   U0196       P049  104.57   Debit Card 2025-08-21
3          T000004   U0133       P042  102.75  Net Banking 2024-07-23
4          T000005   U0047       P038   23.89  Net Banking 2025-10-04
..             ...     ...        ...     ...          ...        ...
995        T000996   U0178       P043   71.11  Credit Card 2025-02-20
996        T000997   U0100       P027   53.96       Wallet 2024-10-02
997        T000998   U0142       P004   76.06  Credit Card 2024-05-29
998        T000999   U0052       P040   62.45  Net Banking 2024-04-06
999        T001000   U0163       P046  123.78       Wallet 2025-01-23

[1000 rows x 6 columns]

In [137]:
df1['city'] = SimpleImputer(strategy='most_frequent').fit_transform(df1[['city']]).ravel()
df1

    user_id            name   age  gender           city registration_date
0     U0001   Vihaan Sharma  35.0   Other         Jaipur        2022-09-08
1     U0002       Sai Reddy  30.0   Other      Hyderabad        2023-11-24
2     U0003    Aarohi Gupta  37.0   Other         Indore        2022-02-02
3     U0004     Aarav Gupta  44.0    Male        Kolkata        2023-06-02
4     U0005     Sara Sharma  30.0   Other        Chennai        2024-01-04
..      ...             ...   ...     ...            ...               ...
195   U0196  Kabir Kulkarni  35.0   Other          Patna        2024-08-01
196   U0197       Kabir Roy  24.0    Male          Thane        2023-12-07
197   U0198      Kabir Bose  33.0  Female  Visakhapatnam        2023-07-07
198   U0199       Meera Roy  32.0    Male      Ghaziabad        2022-02-10
199   U0200      Kiara Nair  22.0   Other         Jaipur        2022-01-27

[200 rows x 6 columns]

In [138]:
df2['payment_type'] = SimpleImputer(strategy='most_frequent').fit_transform(df2[['payment_type']]).ravel()
df2

    transaction_id user_id product_id  amount payment_type       date
0          T000001   U0024       P015   67.67       Wallet 2023-02-12
1          T000002   U0196       P044   76.44          UPI 2023-03-24
2          T000003   U0196       P049  104.57   Debit Card 2025-08-21
3          T000004   U0133       P042  102.75  Net Banking 2024-07-23
4          T000005   U0047       P038   23.89  Net Banking 2025-10-04
..             ...     ...        ...     ...          ...        ...
995        T000996   U0178       P043   71.11  Credit Card 2025-02-20
996        T000997   U0100       P027   53.96       Wallet 2024-10-02
997        T000998   U0142       P004   76.06  Credit Card 2024-05-29
998        T000999   U0052       P040   62.45  Net Banking 2024-04-06
999        T001000   U0163       P046  123.78       Wallet 2025-01-23

[1000 rows x 6 columns]

In [139]:
df1['age'] = KNNImputer(n_neighbors=13).fit_transform(df1[['age']]).ravel()
df1

    user_id            name   age  gender           city registration_date
0     U0001   Vihaan Sharma  35.0   Other         Jaipur        2022-09-08
1     U0002       Sai Reddy  30.0   Other      Hyderabad        2023-11-24
2     U0003    Aarohi Gupta  37.0   Other         Indore        2022-02-02
3     U0004     Aarav Gupta  44.0    Male        Kolkata        2023-06-02
4     U0005     Sara Sharma  30.0   Other        Chennai        2024-01-04
..      ...             ...   ...     ...            ...               ...
195   U0196  Kabir Kulkarni  35.0   Other          Patna        2024-08-01
196   U0197       Kabir Roy  24.0    Male          Thane        2023-12-07
197   U0198      Kabir Bose  33.0  Female  Visakhapatnam        2023-07-07
198   U0199       Meera Roy  32.0    Male      Ghaziabad        2022-02-10
199   U0200      Kiara Nair  22.0   Other         Jaipur        2022-01-27

[200 rows x 6 columns]

## 3. Outlier Handling

In [140]:
num_cols = df1.select_dtypes(include=['int64', 'float64']).columns

for num in num_cols:
    z_scores = (df1[num] - df1[num].mean()) / df1[num].std()
    df4 = df1[(z_scores < 3) & (z_scores > -3)]

print(df4.shape)

(200, 6)

## IQR Method

In [141]:
for num in num_cols:
    q3 = df1[num].quantile(0.75)
    q1 = df1[num].quantile(0.25)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    df5 = df1[(df1[num] >= lower_bound) & (df1[num] <= upper_bound)]
    print(df5.shape)

(198, 6)

IQR method is more relavent than the z-score method because it is more accurate than z-score method

## Windsorization

In [142]:
for num in num_cols:
    lower = np.percentile(df1[num], 5)
    upper = np.percentile(df1[num], 95)
windsorize = np.clip(df1[num], lower, upper)
print(windsorize)

0      35.0
1      30.0
2      37.0
3      44.0
4      30.0
       ...
195    35.0
196    24.0
197    33.0
198    32.0
199    22.0
Name: age, Length: 200, dtype: float64

## 4. Data Transformation

In [143]:
df1['registration_date'] = pd.to_datetime(df1['registration_date'])

df1['day'] = df1['registration_date'].dt.day
df1['month'] = df1['registration_date'].dt.month
df1['year'] = df1['registration_date'].dt.year
df1

,user_id,name,age,gender,city,registration_date,day,month,year
0,U0001,Vihaan Sharma,35.0,Other,Jaipur,2022-09-08,8,9,2022
1,U0002,Sai Reddy,30.0,Other,Hyderabad,2023-11-24,24,11,2023
2,U0003,Aarohi Gupta,37.0,Other,Indore,2022-02-02,2,2,2022
3,U0004,Aarav Gupta,44.0,Male,Kolkata,2023-06-02,2,6,2023
4,U0005,Sara Sharma,30.0,Other,Chennai,2024-01-04,4,1,2024
...,...,...,...,...,...,...,...,...,...
195,U0196,Kabir Kulkarni,35.0,Other,Patna,2024-08-01,1,8,2024
196,U0197,Kabir Roy,24.0,Male,Thane,2023-12-07,7,12,2023
197,U0198,Kabir Bose,33.0,Female,Visakhapatnam,2023-07-07,7,7,2023
198,U0199,Meera Roy,32.0,Male,Ghaziabad,2022-02-10,10,2,2022
199,U0200,Kiara Nair,22.0,Other,Jaipur,2022-01-27,27,1,2022

In [144]:
df1['gender'] = LabelEncoder().fit_transform(df1['gender'])

df1

,user_id,name,age,gender,city,registration_date,day,month,year
0,U0001,Vihaan Sharma,35.0,2,Jaipur,2022-09-08,8,9,2022
1,U0002,Sai Reddy,30.0,2,Hyderabad,2023-11-24,24,11,2023
2,U0003,Aarohi Gupta,37.0,2,Indore,2022-02-02,2,2,2022
3,U0004,Aarav Gupta,44.0,1,Kolkata,2023-06-02,2,6,2023
4,U0005,Sara Sharma,30.0,2,Chennai,2024-01-04,4,1,2024
...,...,...,...,...,...,...,...,...,...
195,U0196,Kabir Kulkarni,35.0,2,Patna,2024-08-01,1,8,2024
196,U0197,Kabir Roy,24.0,1,Thane,2023-12-07,7,12,2023
197,U0198,Kabir Bose,33.0,0,Visakhapatnam,2023-07-07,7,7,2023
198,U0199,Meera Roy,32.0,1,Ghaziabad,2022-02-10,10,2,2022
199,U0200,Kiara Nair,22.0,2,Jaipur,2022-01-27,27,1,2022

In [145]:
one_hot = OneHotEncoder().fit_transform(df1[['gender']])
one_hot_df = pd.DataFrame(one_hot , columns=one_hot.get_feature_names_out())
one_hot_df

AttributeError: 'csr_matrix' object has no attribute 'get_feature_names_out'

In [ ]:
encoder = OrdinalEncoder(categories=[['Male', 'Female' , 'Other']])

df1['age_encoded'] = encoder.fit_transform(df1[['gender']])
df1

,user_id,name,age,gender,city,registration_date,age_encoded
0,U0001,Vihaan Sharma,35,Other,Jaipur,2022-09-08,2.0
1,U0002,Sai Reddy,30,Other,Hyderabad,2023-11-24,2.0
2,U0003,Aarohi Gupta,37,Other,Indore,2022-02-02,2.0
3,U0004,Aarav Gupta,44,Male,Kolkata,2023-06-02,0.0
4,U0005,Sara Sharma,30,Other,Chennai,2024-01-04,2.0
...,...,...,...,...,...,...,...
195,U0196,Kabir Kulkarni,35,Other,Patna,2024-08-01,2.0
196,U0197,Kabir Roy,24,Male,Thane,2023-12-07,0.0
197,U0198,Kabir Bose,33,Female,Visakhapatnam,2023-07-07,1.0
198,U0199,Meera Roy,32,Male,Ghaziabad,2022-02-10,0.0
199,U0200,Kiara Nair,22,Other,Jaipur,2022-01-27,2.0

In [ ]:
bins = pd.cut (df1['age'], bins=[0, 18, 35, 60, np.inf], labels=['young','Freshers', 'Adult', 'Senior'])
bins

0      Freshers
1      Freshers
2         Adult
3         Adult
4      Freshers
         ...
195    Freshers
196    Freshers
197    Freshers
198    Freshers
199    Freshers
Name: age, Length: 200, dtype: category
Categories (4, object): ['young' < 'Freshers' < 'Adult' < 'Senior']

## 5. Feature Scaling

In [ ]:
df1['age'] = StandardScaler().fit_transform(df1[['age']])
df1

,user_id,name,age,gender,city,registration_date,age_encoded
0,U0001,Vihaan Sharma,0.515666,Other,Jaipur,2022-09-08,2.0
1,U0002,Sai Reddy,-0.173727,Other,Hyderabad,2023-11-24,2.0
2,U0003,Aarohi Gupta,0.791424,Other,Indore,2022-02-02,2.0
3,U0004,Aarav Gupta,1.756575,Male,Kolkata,2023-06-02,0.0
4,U0005,Sara Sharma,-0.173727,Other,Chennai,2024-01-04,2.0
...,...,...,...,...,...,...,...
195,U0196,Kabir Kulkarni,0.515666,Other,Patna,2024-08-01,2.0
196,U0197,Kabir Roy,-1.000999,Male,Thane,2023-12-07,0.0
197,U0198,Kabir Bose,0.239909,Female,Visakhapatnam,2023-07-07,1.0
198,U0199,Meera Roy,0.102030,Male,Ghaziabad,2022-02-10,0.0
199,U0200,Kiara Nair,-1.276757,Other,Jaipur,2022-01-27,2.0

In [ ]:
df1['age'] = MinMaxScaler().fit_transform(df1[['age']])
df1

,user_id,name,age,gender,city,registration_date,age_encoded
0,U0001,Vihaan Sharma,0.485714,Other,Jaipur,2022-09-08,2.0
1,U0002,Sai Reddy,0.342857,Other,Hyderabad,2023-11-24,2.0
2,U0003,Aarohi Gupta,0.542857,Other,Indore,2022-02-02,2.0
3,U0004,Aarav Gupta,0.742857,Male,Kolkata,2023-06-02,0.0
4,U0005,Sara Sharma,0.342857,Other,Chennai,2024-01-04,2.0
...,...,...,...,...,...,...,...
195,U0196,Kabir Kulkarni,0.485714,Other,Patna,2024-08-01,2.0
196,U0197,Kabir Roy,0.171429,Male,Thane,2023-12-07,0.0
197,U0198,Kabir Bose,0.428571,Female,Visakhapatnam,2023-07-07,1.0
198,U0199,Meera Roy,0.400000,Male,Ghaziabad,2022-02-10,0.0
199,U0200,Kiara Nair,0.114286,Other,Jaipur,2022-01-27,2.0

## 6. Feature Construction

In [ ]:
df2['date'] = pd.to_datetime(df2['date'])

df2['year_month'] = df2['date'].dt.to_period('M')

agg = df2.groupby('user_id').agg(
    total_spend=('amount', 'sum'),
    active_months=('year_month', 'nunique')
).reset_index()

agg['avg_monthly_spend'] = agg['total_spend'] / agg['active_months']

agg

    user_id  total_spend  active_months  avg_monthly_spend
0     U0001       232.42              3          77.473333
1     U0002       389.04              3         129.680000
2     U0003       162.39              4          40.597500
3     U0004       300.64              3         100.213333
4     U0005       347.69              6          57.948333
..      ...          ...            ...                ...
195   U0196       622.98              7          88.997143
196   U0197       244.42              4          61.105000
197   U0198       161.15              2          80.575000
198   U0199       684.77              9          76.085556
199   U0200       342.89              6          57.148333

[200 rows x 4 columns]

In [ ]:
agg = df2.groupby('user_id').agg(
    total_transactions=('date', 'count'),
    active_months=('year_month', 'nunique')
).reset_index()

agg['purchase_frequency'] = agg['total_transactions'] / agg['active_months']

agg

    user_id  total_transactions  active_months  purchase_frequency
0     U0001                   3              3                 1.0
1     U0002                   6              3                 2.0
2     U0003                   4              4                 1.0
3     U0004                   3              3                 1.0
4     U0005                   6              6                 1.0
..      ...                 ...            ...                 ...
195   U0196                   7              7                 1.0
196   U0197                   4              4                 1.0
197   U0198                   3              2                 1.5
198   U0199                   9              9                 1.0
199   U0200                   6              6                 1.0

[200 rows x 4 columns]

In [ ]:
current_date = df2['date'].max()

agg = df2.groupby('user_id').agg(
    last_purchase_date=('date', 'max')
).reset_index()

agg['days_since_last_purchase'] = (current_date - agg['last_purchase_date']).dt.days

agg

    user_id last_purchase_date  days_since_last_purchase
0     U0001         2024-08-20                       438
1     U0002         2024-04-27                       553
2     U0003         2025-11-01                         0
3     U0004         2024-04-03                       577
4     U0005         2025-06-22                       132
..      ...                ...                       ...
195   U0196         2025-08-21                        72
196   U0197         2025-10-26                         6
197   U0198         2025-10-29                         3
198   U0199         2025-08-12                        81
199   U0200         2025-08-24                        69

[200 rows x 3 columns]

In [147]:
profile = ProfileReport(df1, title="Data Profiling Report", explorative=True)
profile.to_file("data_profiling_report.html")

100%|██████████| 9/9 [00:00<00:00, 189.92it/s]0<00:00, 29.88it/s, Describe variable: year]
Summarize dataset:  69%|██████▉   | 11/16 [00:00<00:00, 29.88it/s, Calculate auto correlation]c:\Users\RUDRA JATIN GAYWALA\AppData\Local\Programs\Python\Python313\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2 7 0 0 0 8 4 4 5 5 6 7 4 1 3 0 0 0 3 4 4 2 2 4 6 9 6 8 6 9 7 0 7 4 1 4 0
 9 3 7 3 7 5 6 4 9 3 3 4 2 7 4 4 1 9 1 6 3 0 4 9 0 0 2 0 6 2 0 5 4 2 5 4 5
 5 0 9 4 8 4 9 9 5 5 6 3 0 7 1 8 0 9 7 1 0 4 5 2 5 9 4 1 9 2 0 4 7 0 5 6 2
 5 5 9 5 5 0 9 3 4 9 3 1 7 2 9 7 3 6 1 8 1 1 3 0 2 8 8 6 3 2 6 8 7 2 6 4 4
 3 4 3 2 3 2 6 7 7 9 2 3 4 4 4 4 7 9 2 8 1 4 6 4 8 0 0 2 8 3 4 8 4 9 8 6 0
 8 8 2 2 8 7 0 3 5 5 0 1 1 2 8]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
c:\Users\RUDRA JATIN GAYWALA\AppData\Local\Programs\Python\Python313\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[7 9 0 4 0 6 9 2 3 0 1 4 0 4 8 6 5 8 3 0 4 0 7 1 3 3 1 0 7 9 2 0 5 7 5 3 7
 1 3 4 0 1 6 5 1 3 8 0 1 2 2 0 5 5 1 3 0 5 0 9 8 1 3 7 7 6 0 6 9 3 0 1 3 8
 7 9 4 8 5 5 2 0 5 1 6 0 6 4 6 0 8 3 9 9 4 0 4 0 0 2 0 9 6 0 9 5 7 3 1 2 4
 8 2 3 7 5 4 4 7 9 6 1 2 0 8 6 1 9 0 1 6 0 5 6 0 3 0 1 0 2 0 0 8 5 3 2 7 6
 0 2 1 9 0 7 1 7 2 2 0 9 3 8 4 3 8 8 9 4 9 7 9 5 7 3 5 3 8 6 9 2 6 6 5 6 9
 7 6 4 4 2 9 6 1 5 4 6 9 5 0 0]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
c:\Users\RUDRA JATIN GAYWALA\AppData\Local\Programs\Python\Python313\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 4 0 4 9 4 0 0 9 9 0 9 0 9 4 0 4 0 9 4 9 4 0 4 0 9 9 4 9 4 0 0 9 4 4 4 0
 0 0 4 9 4 0 4 0 9 0 9 9 0 4 9 0 0 4 9 4 9 4 4 0 0 4 9 4 9 0 4 4 0 0 0 0 0
 4 0 9 0 0 9 9 9 4 0 4 0 0 9 9 0 0 9 0 4 9 4 9 0 9 0 0 4 9 9 0 0 4 9 4 4 4
 0 9 0 4 0 0 0 0 4 9 4 4 9 0 0 0 4 4 0 9 0 4 0 4 9 0 0 0 4 9 0 4 0 0 4 4 4
 4 0 9 4 0 9 4 4 9 9 9 0 4 0 4 4 4 0 0 4 0 0 0 0 9 9 0 0 0 4 0 0 4 9 4 0 0
 4 9 0 0 4 4 9 4 9 0 9 4 4 0 0]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
Summarize dataset: 100%|██████████| 27/27 [00:02<00:00, 11.39it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.03s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 113.08it/s]

In [150]:
df1.to_csv('final_cleaned_dataset.csv', index=False)